services:
    ddr53-client:
      image: ghcr.io/bz0qyz/bz0qyz/ddr53-client:v1.1.1
      container_name: ddr53-client
      restart: unless-stopped
      volumes:
        - ./ddr53-client.conf:/etc/ddr53-client.conf
      environment:
        - DAEMON_INTERVAL=30

